apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: m7f5dv4bb-python 
  janus-idp.io/tekton: m7f5dv4bb-python
  backstage.io/kubernetes-id: m7f5dv4bb-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: m7f5dv4bb-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml